/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface DashboardPage {
    }
    interface LoginPage {
    }
    interface NotFoundPage {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDashboardPageElement extends Components.DashboardPage, HTMLStencilElement {
    }
    var HTMLDashboardPageElement: {
        prototype: HTMLDashboardPageElement;
        new (): HTMLDashboardPageElement;
    };
    interface HTMLLoginPageElement extends Components.LoginPage, HTMLStencilElement {
    }
    var HTMLLoginPageElement: {
        prototype: HTMLLoginPageElement;
        new (): HTMLLoginPageElement;
    };
    interface HTMLNotFoundPageElement extends Components.NotFoundPage, HTMLStencilElement {
    }
    var HTMLNotFoundPageElement: {
        prototype: HTMLNotFoundPageElement;
        new (): HTMLNotFoundPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "dashboard-page": HTMLDashboardPageElement;
        "login-page": HTMLLoginPageElement;
        "not-found-page": HTMLNotFoundPageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface DashboardPage {
    }
    interface LoginPage {
    }
    interface NotFoundPage {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "dashboard-page": DashboardPage;
        "login-page": LoginPage;
        "not-found-page": NotFoundPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "dashboard-page": LocalJSX.DashboardPage & JSXBase.HTMLAttributes<HTMLDashboardPageElement>;
            "login-page": LocalJSX.LoginPage & JSXBase.HTMLAttributes<HTMLLoginPageElement>;
            "not-found-page": LocalJSX.NotFoundPage & JSXBase.HTMLAttributes<HTMLNotFoundPageElement>;
        }
    }
}
