/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnalyticsDashboard {
    }
    interface AppRoot {
    }
    interface CreatePerformanceCycle {
    }
    interface DashboardPage {
    }
    interface EmployeeDashboard {
    }
    interface EmployeeFeedbackForm {
    }
    interface LoginPage {
    }
    interface ManagerDashboard {
    }
    interface ManagerFeedbackForm {
    }
    interface NotFoundPage {
    }
    interface SignupPage {
    }
    interface TeamFeedbackPage {
    }
}
declare global {
    interface HTMLAnalyticsDashboardElement extends Components.AnalyticsDashboard, HTMLStencilElement {
    }
    var HTMLAnalyticsDashboardElement: {
        prototype: HTMLAnalyticsDashboardElement;
        new (): HTMLAnalyticsDashboardElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCreatePerformanceCycleElement extends Components.CreatePerformanceCycle, HTMLStencilElement {
    }
    var HTMLCreatePerformanceCycleElement: {
        prototype: HTMLCreatePerformanceCycleElement;
        new (): HTMLCreatePerformanceCycleElement;
    };
    interface HTMLDashboardPageElement extends Components.DashboardPage, HTMLStencilElement {
    }
    var HTMLDashboardPageElement: {
        prototype: HTMLDashboardPageElement;
        new (): HTMLDashboardPageElement;
    };
    interface HTMLEmployeeDashboardElement extends Components.EmployeeDashboard, HTMLStencilElement {
    }
    var HTMLEmployeeDashboardElement: {
        prototype: HTMLEmployeeDashboardElement;
        new (): HTMLEmployeeDashboardElement;
    };
    interface HTMLEmployeeFeedbackFormElement extends Components.EmployeeFeedbackForm, HTMLStencilElement {
    }
    var HTMLEmployeeFeedbackFormElement: {
        prototype: HTMLEmployeeFeedbackFormElement;
        new (): HTMLEmployeeFeedbackFormElement;
    };
    interface HTMLLoginPageElement extends Components.LoginPage, HTMLStencilElement {
    }
    var HTMLLoginPageElement: {
        prototype: HTMLLoginPageElement;
        new (): HTMLLoginPageElement;
    };
    interface HTMLManagerDashboardElement extends Components.ManagerDashboard, HTMLStencilElement {
    }
    var HTMLManagerDashboardElement: {
        prototype: HTMLManagerDashboardElement;
        new (): HTMLManagerDashboardElement;
    };
    interface HTMLManagerFeedbackFormElement extends Components.ManagerFeedbackForm, HTMLStencilElement {
    }
    var HTMLManagerFeedbackFormElement: {
        prototype: HTMLManagerFeedbackFormElement;
        new (): HTMLManagerFeedbackFormElement;
    };
    interface HTMLNotFoundPageElement extends Components.NotFoundPage, HTMLStencilElement {
    }
    var HTMLNotFoundPageElement: {
        prototype: HTMLNotFoundPageElement;
        new (): HTMLNotFoundPageElement;
    };
    interface HTMLSignupPageElement extends Components.SignupPage, HTMLStencilElement {
    }
    var HTMLSignupPageElement: {
        prototype: HTMLSignupPageElement;
        new (): HTMLSignupPageElement;
    };
    interface HTMLTeamFeedbackPageElement extends Components.TeamFeedbackPage, HTMLStencilElement {
    }
    var HTMLTeamFeedbackPageElement: {
        prototype: HTMLTeamFeedbackPageElement;
        new (): HTMLTeamFeedbackPageElement;
    };
    interface HTMLElementTagNameMap {
        "analytics-dashboard": HTMLAnalyticsDashboardElement;
        "app-root": HTMLAppRootElement;
        "create-performance-cycle": HTMLCreatePerformanceCycleElement;
        "dashboard-page": HTMLDashboardPageElement;
        "employee-dashboard": HTMLEmployeeDashboardElement;
        "employee-feedback-form": HTMLEmployeeFeedbackFormElement;
        "login-page": HTMLLoginPageElement;
        "manager-dashboard": HTMLManagerDashboardElement;
        "manager-feedback-form": HTMLManagerFeedbackFormElement;
        "not-found-page": HTMLNotFoundPageElement;
        "signup-page": HTMLSignupPageElement;
        "team-feedback-page": HTMLTeamFeedbackPageElement;
    }
}
declare namespace LocalJSX {
    interface AnalyticsDashboard {
    }
    interface AppRoot {
    }
    interface CreatePerformanceCycle {
    }
    interface DashboardPage {
    }
    interface EmployeeDashboard {
    }
    interface EmployeeFeedbackForm {
    }
    interface LoginPage {
    }
    interface ManagerDashboard {
    }
    interface ManagerFeedbackForm {
    }
    interface NotFoundPage {
    }
    interface SignupPage {
    }
    interface TeamFeedbackPage {
    }
    interface IntrinsicElements {
        "analytics-dashboard": AnalyticsDashboard;
        "app-root": AppRoot;
        "create-performance-cycle": CreatePerformanceCycle;
        "dashboard-page": DashboardPage;
        "employee-dashboard": EmployeeDashboard;
        "employee-feedback-form": EmployeeFeedbackForm;
        "login-page": LoginPage;
        "manager-dashboard": ManagerDashboard;
        "manager-feedback-form": ManagerFeedbackForm;
        "not-found-page": NotFoundPage;
        "signup-page": SignupPage;
        "team-feedback-page": TeamFeedbackPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "analytics-dashboard": LocalJSX.AnalyticsDashboard & JSXBase.HTMLAttributes<HTMLAnalyticsDashboardElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "create-performance-cycle": LocalJSX.CreatePerformanceCycle & JSXBase.HTMLAttributes<HTMLCreatePerformanceCycleElement>;
            "dashboard-page": LocalJSX.DashboardPage & JSXBase.HTMLAttributes<HTMLDashboardPageElement>;
            "employee-dashboard": LocalJSX.EmployeeDashboard & JSXBase.HTMLAttributes<HTMLEmployeeDashboardElement>;
            "employee-feedback-form": LocalJSX.EmployeeFeedbackForm & JSXBase.HTMLAttributes<HTMLEmployeeFeedbackFormElement>;
            "login-page": LocalJSX.LoginPage & JSXBase.HTMLAttributes<HTMLLoginPageElement>;
            "manager-dashboard": LocalJSX.ManagerDashboard & JSXBase.HTMLAttributes<HTMLManagerDashboardElement>;
            "manager-feedback-form": LocalJSX.ManagerFeedbackForm & JSXBase.HTMLAttributes<HTMLManagerFeedbackFormElement>;
            "not-found-page": LocalJSX.NotFoundPage & JSXBase.HTMLAttributes<HTMLNotFoundPageElement>;
            "signup-page": LocalJSX.SignupPage & JSXBase.HTMLAttributes<HTMLSignupPageElement>;
            "team-feedback-page": LocalJSX.TeamFeedbackPage & JSXBase.HTMLAttributes<HTMLTeamFeedbackPageElement>;
        }
    }
}
